name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@672cf56c8b828e444b6e7906d0ee355c7ec1dea9 # main
        with:
          repository: openstack/octavia
          ref: 79cf1f787fa9c03adba8575dc94324b97963f84e # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@672cf56c8b828e444b6e7906d0ee355c7ec1dea9 # main
        with:
          repository: openstack/ovn-octavia-provider
          ref: 732466071706ef5c3e651ece1bbb16380ed4da0f # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@672cf56c8b828e444b6e7906d0ee355c7ec1dea9 # main
        with:
          image-name: octavia
          build-contexts: |
            octavia=openstack/octavia
            ovn-octavia-provider=openstack/ovn-octavia-provider
          push: ${{ github.event_name != 'pull_request' }}
