name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@db1fb3032d9f9a0a3ad24819e88c1b82fab4231c # main
        with:
          repository: openstack/ovn-octavia-provider
          ref: f673dc05ef46d46fb1ed10004a8535a63396c603 # stable/2024.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@db1fb3032d9f9a0a3ad24819e88c1b82fab4231c # main
        with:
          image-name: octavia
          build-contexts: |
            ovn-octavia-provider=openstack/ovn-octavia-provider
          push: ${{ github.event_name != 'pull_request' }}
