name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          repository: openstack/octavia
          ref: 6713b15de314f1971907adb35a8e130e838bfff5 # unmaintained/2023.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          repository: openstack/ovn-octavia-provider
          ref: 2564f92911840664df8a424697e7c7c8dd9c9865 # unmaintained/2023.1

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          image-name: octavia
          build-contexts: |
            octavia=openstack/octavia
            ovn-octavia-provider=openstack/ovn-octavia-provider
          push: ${{ github.event_name != 'pull_request' }}
